#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("com.dbeattie.Resource", IsApplication=false)]

namespace com.dbeattie
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public static int sb__in = 2130968576;
			
			// aapt resource value: 0x7f040001
			public static int sb__out = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f060000
			public static int sb__is_phone = 2131099648;
			
			// aapt resource value: 0x7f060001
			public static int sb__is_swipeable = 2131099649;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f070003
			public static int sb__action_bg_color = 2131165187;
			
			// aapt resource value: 0x7f070002
			public static int sb__action_text_color = 2131165186;
			
			// aapt resource value: 0x7f070000
			public static int sb__background = 2131165184;
			
			// aapt resource value: 0x7f070001
			public static int sb__text_color = 2131165185;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f080000
			public static int sb__bg_corner_radius = 2131230720;
			
			// aapt resource value: 0x7f080008
			public static int sb__max_width = 2131230728;
			
			// aapt resource value: 0x7f080007
			public static int sb__min_width = 2131230727;
			
			// aapt resource value: 0x7f080001
			public static int sb__offset = 2131230721;
			
			// aapt resource value: 0x7f080002
			public static int sb__text_padding_bottom = 2131230722;
			
			// aapt resource value: 0x7f080003
			public static int sb__text_padding_left = 2131230723;
			
			// aapt resource value: 0x7f080005
			public static int sb__text_padding_right = 2131230725;
			
			// aapt resource value: 0x7f080004
			public static int sb__text_padding_top = 2131230724;
			
			// aapt resource value: 0x7f080006
			public static int sb__text_size = 2131230726;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int sb__bg = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int sb__btn_bg = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0001
			public static int sb__action = 2131361793;
			
			// aapt resource value: 0x7f0a0000
			public static int sb__text = 2131361792;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Interpolator
		{
			
			// aapt resource value: 0x7f050000
			public static int sb__accelerate_cubic = 2131034112;
			
			// aapt resource value: 0x7f050001
			public static int sb__decelerate_cubic = 2131034113;
			
			static Interpolator()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Interpolator()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public static int sb__template = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f090000
			public static int Snackbar = 2131296256;
			
			// aapt resource value: 0x7f090001
			public static int Snackbar_Text = 2131296257;
			
			// aapt resource value: 0x7f090002
			public static int Snackbar_Text_Action = 2131296258;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
